#!/usr/bin/env python3
"""Read and write the OneDrop OTA manifests.

Two files live side by side in the releases directory:

    version.json    an object keyed by platform, holding the current build
    releases.json   a flat array of every build ever published

Every client and the downloads page read both, so they are the one artefact in
this repository that must never be edited by hand or generated by PowerShell's
ConvertTo-Json, which reorders keys and turns a one-element array into an object
with `value` and `Count` fields. That corruption is silent, produces a manifest
that still parses, and breaks every client's update check at once -- so it is
detected explicitly below rather than hoped against.
"""

from __future__ import annotations

import base64
import hashlib
import json
import os
import sys
import urllib.error
import urllib.request
from typing import Any

PLATFORMS = (
    "onedropAndroid",
    "onedropWindows",
    "onedropMacos",
    "onedropMacosIntel",
    "onedropLinux",
    "onedropUbuntuTouch",
)

ENTRY_REQUIRED = (
    "platform",
    "version",
    "buildNumber",
    "label",
    "file",
    "sizeBytes",
    "sha256",
    "publishedAt",
)

# The same fields minus `platform`, which is the key in version.json.
VERSION_BLOCK_REQUIRED = ENTRY_REQUIRED[1:]

DOWNLOADS_URL = "https://onedrop.aml.one/downloads"
DOWNLOADS_PAGE_URL = "https://onedrop.aml.one/downloads"


def normalize_changelog(value: Any) -> list[str] | None:
    if value is None:
        return None
    if isinstance(value, list):
        out = [str(x).strip() for x in value if str(x).strip()]
        return out or None
    if isinstance(value, str):
        # A single-entry changelog that came back from PowerShell as a bare
        # string rather than an array.
        text = value.strip()
        return [text] if text else None
    return None


def flatten_releases(releases: Any) -> list[dict[str, Any]]:
    """Unwraps the `value`/`Count` nesting ConvertTo-Json produces."""
    flat: list[dict[str, Any]] = []

    def walk(items: Any) -> None:
        if not isinstance(items, list):
            return
        for item in items:
            if not isinstance(item, dict):
                continue
            if "value" in item and "platform" not in item:
                walk(item["value"])
            elif "platform" in item and "buildNumber" in item:
                flat.append(dict(item))

    walk(releases if isinstance(releases, list) else [])
    return flat


def normalize_entry(entry: dict[str, Any]) -> dict[str, Any]:
    out = dict(entry)
    if "changelog" in out:
        normalized = normalize_changelog(out["changelog"])
        if normalized:
            out["changelog"] = normalized
        else:
            out.pop("changelog", None)
    if isinstance(out.get("sha256"), str):
        out["sha256"] = out["sha256"].lower()
    return out


def load_json(path: str, fallback: Any) -> Any:
    if not os.path.isfile(path):
        return fallback
    # utf-8-sig: a manifest that once passed through a Windows editor may carry
    # a BOM, which json.load rejects outright.
    with open(path, encoding="utf-8-sig") as f:
        return json.load(f)


def write_json(path: str, data: Any) -> None:
    parent = os.path.dirname(path)
    if parent:
        os.makedirs(parent, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)
        f.write("\n")
    os.chmod(path, 0o644)


def validate_entry_dict(entry: Any, *, label: str = "entry") -> list[str]:
    errors: list[str] = []
    if not isinstance(entry, dict):
        return [f"{label}: must be a JSON object"]

    for key in ENTRY_REQUIRED:
        if key not in entry:
            errors.append(f"{label}: missing required field '{key}'")

    platform = entry.get("platform")
    if platform is not None and platform not in PLATFORMS:
        errors.append(
            f"{label}: invalid platform '{platform}'. OneDrop writes only "
            f"{', '.join(PLATFORMS)}."
        )

    sha = entry.get("sha256")
    if isinstance(sha, str) and sha and len(sha) != 64:
        errors.append(f"{label}: sha256 must be 64 hex characters, got {len(sha)}")

    build = entry.get("buildNumber")
    if build is not None and (not isinstance(build, int) or build <= 0):
        errors.append(f"{label}: buildNumber must be a positive integer")

    if "changelog" in entry:
        changelog = entry["changelog"]
        if not isinstance(changelog, list):
            errors.append(
                f"{label}: changelog must be a JSON array of strings, got "
                f"{type(changelog).__name__}"
            )
        else:
            for idx, line in enumerate(changelog):
                if not isinstance(line, str):
                    errors.append(
                        f"{label}: changelog[{idx}] must be a string, got "
                        f"{type(line).__name__}"
                    )
                elif not line.strip():
                    errors.append(f"{label}: changelog[{idx}] must not be blank")

    if "value" in entry and "platform" not in entry:
        errors.append(f"{label}: PowerShell value/Count corruption detected")

    return errors


def validate_version_manifest(version: Any) -> list[str]:
    errors: list[str] = []
    if not isinstance(version, dict):
        return ["version.json root must be a JSON object"]

    for plat, block in version.items():
        if plat not in PLATFORMS:
            errors.append(f"version.json: unknown platform key '{plat}'")
            continue
        # null means "nothing published for this platform yet", which is a
        # legitimate state for a product that has not shipped everywhere.
        if block is None:
            continue
        if not isinstance(block, dict):
            errors.append(f"version.json[{plat}]: must be an object or null")
            continue
        for key in VERSION_BLOCK_REQUIRED:
            if key not in block:
                errors.append(f"version.json[{plat}]: missing '{key}'")
        if "changelog" in block and not isinstance(block["changelog"], list):
            errors.append(
                f"version.json[{plat}].changelog must be a JSON array, got "
                f"{type(block['changelog']).__name__}"
            )
    return errors


def has_powershell_json_corruption(value: Any) -> bool:
    if isinstance(value, dict):
        if "value" in value and "Count" in value and "platform" not in value:
            return True
        return any(has_powershell_json_corruption(v) for v in value.values())
    if isinstance(value, list):
        return any(has_powershell_json_corruption(v) for v in value)
    return False


def validate_releases_list(releases: Any) -> list[str]:
    errors: list[str] = []
    if not isinstance(releases, list):
        return ["releases.json root must be a JSON array"]

    if has_powershell_json_corruption(releases):
        errors.append(
            "releases.json: PowerShell value/Count corruption detected - "
            "re-merge with scripts/release-manifest.py"
        )

    flat = flatten_releases(releases)
    if len(flat) != len(releases):
        errors.append(
            f"releases.json: expected a flat array, found {len(releases)} "
            f"top-level item(s) holding {len(flat)} release(s)"
        )

    seen: set[tuple[Any, Any]] = set()
    for idx, entry in enumerate(flat):
        label = f"releases.json[{idx}]"
        errors.extend(validate_entry_dict(entry, label=label))
        key = (entry.get("platform"), entry.get("buildNumber"))
        if key in seen:
            errors.append(f"{label}: duplicate platform/buildNumber {key}")
        seen.add(key)

    return errors


def sha256_of(path: str) -> str:
    digest = hashlib.sha256()
    with open(path, "rb") as f:
        # Hashed in pieces: a release archive does not belong in memory.
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def validate_artifacts(dir_path: str) -> list[str]:
    """Checks every referenced file exists and matches its recorded size and hash.

    This is what catches a truncated upload. A manifest can be perfectly valid
    JSON and still point at half a file, and the client will download it, fail
    verification, and refuse to update until somebody republishes.
    """
    errors: list[str] = []
    releases = flatten_releases(load_json(os.path.join(dir_path, "releases.json"), []))
    version = load_json(os.path.join(dir_path, "version.json"), {})

    checked: dict[str, tuple[int, str]] = {}
    entries = list(releases)
    if isinstance(version, dict):
        for plat, block in version.items():
            if isinstance(block, dict):
                entries.append(dict(block, platform=plat))

    for entry in entries:
        name = entry.get("file")
        if not isinstance(name, str) or not name:
            continue
        path = os.path.join(dir_path, name)
        if not os.path.isfile(path):
            errors.append(f"{name}: referenced by the manifest but not on disk")
            continue

        if name not in checked:
            checked[name] = (os.path.getsize(path), sha256_of(path))
        size, digest = checked[name]

        if entry.get("sizeBytes") != size:
            errors.append(
                f"{name}: manifest says {entry.get('sizeBytes')} bytes, file is {size}"
            )
        recorded = str(entry.get("sha256", "")).lower()
        if recorded and recorded != digest:
            errors.append(f"{name}: sha256 mismatch (file is {digest})")

    return errors


def validate_dir(dir_path: str, *, artifacts: bool = False) -> list[str]:
    errors: list[str] = []
    version_path = os.path.join(dir_path, "version.json")
    releases_path = os.path.join(dir_path, "releases.json")

    if not os.path.isdir(dir_path):
        return [f"manifest directory not found: {dir_path}"]
    if not os.path.isfile(version_path):
        errors.append(f"missing {version_path}")
    if not os.path.isfile(releases_path):
        errors.append(f"missing {releases_path}")
    if errors:
        return errors

    errors.extend(validate_version_manifest(load_json(version_path, None)))
    errors.extend(validate_releases_list(load_json(releases_path, None)))
    if not errors and artifacts:
        errors.extend(validate_artifacts(dir_path))
    return errors


def assert_valid_dir(dir_path: str) -> None:
    errors = validate_dir(dir_path)
    if errors:
        print("Release manifest validation failed:", file=sys.stderr)
        for err in errors:
            print(f"  - {err}", file=sys.stderr)
        raise SystemExit(1)


def merge_entry(dir_path: str, entry: dict[str, Any]) -> None:
    entry = normalize_entry(entry)
    errors = validate_entry_dict(entry)
    if errors:
        print("Refusing to merge an invalid entry:", file=sys.stderr)
        for err in errors:
            print(f"  - {err}", file=sys.stderr)
        raise SystemExit(1)

    platform = entry["platform"]
    version_path = os.path.join(dir_path, "version.json")
    releases_path = os.path.join(dir_path, "releases.json")

    version: dict[str, Any] = load_json(version_path, {})
    releases = flatten_releases(load_json(releases_path, []))

    # version.json only ever moves forward. Republishing an older build to
    # recover from a bad release is done by purging the newer entry first, not
    # by quietly overwriting the current pointer with something older.
    existing = version.get(platform)
    if not isinstance(existing, dict) or entry["buildNumber"] >= int(
        existing.get("buildNumber", 0)
    ):
        version[platform] = {
            k: entry[k] for k in VERSION_BLOCK_REQUIRED if k in entry
        }
        if "changelog" in entry:
            version[platform]["changelog"] = entry["changelog"]

    releases = [entry] + [
        r
        for r in releases
        if not (
            r.get("platform") == platform
            and r.get("buildNumber") == entry["buildNumber"]
        )
    ]
    releases = [normalize_entry(r) for r in releases]
    releases.sort(key=lambda r: r.get("buildNumber", 0), reverse=True)

    write_json(version_path, version)
    write_json(releases_path, releases)
    assert_valid_dir(dir_path)


def repair_dir(dir_path: str) -> int:
    version_path = os.path.join(dir_path, "version.json")
    releases_path = os.path.join(dir_path, "releases.json")

    releases = flatten_releases(load_json(releases_path, []))
    fixed = 0

    for release in releases:
        before = release.get("changelog")
        normalized = normalize_changelog(before)
        if normalized != before:
            fixed += 1
        if normalized:
            release["changelog"] = normalized
        else:
            release.pop("changelog", None)

    deduped: dict[tuple[Any, Any], dict[str, Any]] = {}
    for release in releases:
        deduped[(release.get("platform"), release.get("buildNumber"))] = normalize_entry(
            release
        )
    write_json(
        releases_path,
        sorted(deduped.values(), key=lambda r: r.get("buildNumber", 0), reverse=True),
    )

    version: dict[str, Any] = load_json(version_path, {})
    for plat in PLATFORMS:
        block = version.get(plat)
        if not isinstance(block, dict):
            # Keep every known platform present, so the manifest documents what
            # exists rather than only what has shipped.
            version.setdefault(plat, None)
            continue
        if "changelog" in block:
            before = block["changelog"]
            normalized = normalize_changelog(before)
            if normalized != before:
                fixed += 1
            if normalized:
                block["changelog"] = normalized
            else:
                block.pop("changelog", None)
    write_json(version_path, version)

    assert_valid_dir(dir_path)
    return fixed


def purge_platform(dir_path: str, platform: str) -> list[str]:
    """Removes every entry for a platform. Returns the artifact filenames."""
    version_path = os.path.join(dir_path, "version.json")
    releases_path = os.path.join(dir_path, "releases.json")

    releases = flatten_releases(load_json(releases_path, []))
    removed = [
        str(r.get("file"))
        for r in releases
        if r.get("platform") == platform and r.get("file")
    ]
    releases = [normalize_entry(r) for r in releases if r.get("platform") != platform]
    releases.sort(key=lambda r: r.get("buildNumber", 0), reverse=True)
    write_json(releases_path, releases)

    version: dict[str, Any] = load_json(version_path, {})
    if isinstance(version, dict) and platform in version:
        version[platform] = None
        write_json(version_path, version)

    assert_valid_dir(dir_path)
    return removed


def prepare_entry_file(path: str) -> None:
    with open(path, encoding="utf-8-sig") as f:
        entry = normalize_entry(json.load(f))
    errors = validate_entry_dict(entry)
    if errors:
        print("Release entry validation failed:", file=sys.stderr)
        for err in errors:
            print(f"  - {err}", file=sys.stderr)
        raise SystemExit(1)
    write_json(path, entry)


def write_entry_from_b64(out_path: str, b64: str) -> None:
    """Writes an entry handed over as base64.

    The publish script sends the entry to the release host this way because it
    travels through an SSH command line, where quoting a JSON document with
    embedded changelog text is a reliable source of corruption.
    """
    entry = normalize_entry(json.loads(base64.b64decode(b64).decode("utf-8")))
    errors = validate_entry_dict(entry)
    if errors:
        print("Release entry validation failed:", file=sys.stderr)
        for err in errors:
            print(f"  - {err}", file=sys.stderr)
        raise SystemExit(1)
    write_json(out_path, entry)


def check_downloads_page(url: str = DOWNLOADS_PAGE_URL) -> list[str]:
    errors: list[str] = []
    try:
        with urllib.request.urlopen(url, timeout=30) as response:
            body = response.read(200_000).decode("utf-8", errors="replace")
            content_type = response.headers.get("Content-Type", "")
    except urllib.error.URLError as exc:
        return [f"downloads page unreachable: {exc}"]

    lower = body.lower()
    if "text/html" not in content_type.lower():
        errors.append(f"downloads page did not return HTML ({content_type!r})")
    if "<html" not in lower and "<!doctype" not in lower:
        errors.append(f"downloads page missing an HTML document marker ({url})")
    if "OneDrop" not in body:
        errors.append(f"downloads page missing expected branding ({url})")
    if 'data-downloads-page="onedrop"' not in body:
        errors.append(f"downloads page missing expected marker ({url})")
    if "Downloads are unavailable" in body:
        errors.append("downloads page rendered its manifest-missing state")
    return errors


def check_manifest_urls(base: str = DOWNLOADS_URL) -> list[str]:
    """Fetches the two manifests the way a client would."""
    errors: list[str] = []
    for name, validator in (
        ("version.json", validate_version_manifest),
        ("releases.json", validate_releases_list),
    ):
        url = f"{base.rstrip('/')}/{name}"
        try:
            with urllib.request.urlopen(url, timeout=30) as response:
                document = json.loads(response.read().decode("utf-8"))
        except (urllib.error.URLError, json.JSONDecodeError) as exc:
            errors.append(f"{name} unreachable or unparseable: {exc}")
            continue
        errors.extend(f"{url}: {err}" for err in validator(document))
    return errors


def self_test() -> None:
    """Regression checks for the failure modes that have actually happened."""
    entry = {
        "platform": "onedropAndroid",
        "version": "1.0.1",
        "buildNumber": 10001,
        "label": "v1.0.1-260812",
        "file": "onedrop-android-arm64-v1.0.1-260812.apk",
        "sizeBytes": 1,
        "sha256": "A" * 64,
        "publishedAt": "2026-08-12T00:00:00Z",
        "changelog": "[bugfix] a single line that arrived as a bare string",
    }

    fixed = normalize_entry(entry)
    assert isinstance(fixed["changelog"], list), fixed["changelog"]
    assert fixed["sha256"] == "a" * 64
    assert validate_entry_dict(entry), "a bare-string changelog must fail validation"
    assert not validate_entry_dict(fixed), "a normalised entry must pass"

    corrupted = [
        {
            "value": [dict(fixed, changelog=["x"])],
            "Count": 1,
        }
    ]
    assert validate_releases_list(corrupted), "value/Count nesting must fail"
    assert not validate_releases_list([fixed])

    assert validate_entry_dict(dict(fixed, platform="android")), (
        "MessageMe's platform keys must be rejected here"
    )
    assert validate_entry_dict(dict(fixed, sha256="abc")), "a short hash must fail"
    assert validate_entry_dict(dict(fixed, buildNumber=0)), "build zero must fail"

    assert not validate_version_manifest({plat: None for plat in PLATFORMS})
    assert validate_version_manifest({"android": None}), "unknown keys must fail"

    duplicate = [fixed, dict(fixed)]
    assert validate_releases_list(duplicate), "duplicate build numbers must fail"


USAGE = """Usage:
  release-manifest.py merge <dir> <entry.json>
  release-manifest.py repair <dir>
  release-manifest.py validate <dir> [--artifacts]
  release-manifest.py validate-entry <entry.json>
  release-manifest.py prepare-entry <entry.json>
  release-manifest.py write-entry-b64 <out.json>   (reads ENTRY_B64)
  release-manifest.py purge-platform <dir> <platform>
  release-manifest.py check-downloads [url]
  release-manifest.py check-manifests [downloads url]
  release-manifest.py --self-test"""


def main() -> int:
    if len(sys.argv) < 2:
        print(USAGE, file=sys.stderr)
        return 2

    cmd = sys.argv[1]

    if cmd == "check-downloads":
        url = sys.argv[2] if len(sys.argv) > 2 else DOWNLOADS_PAGE_URL
        errors = check_downloads_page(url)
        if errors:
            print("Downloads page check failed:", file=sys.stderr)
            for err in errors:
                print(f"  - {err}", file=sys.stderr)
            return 1
        print("Downloads page OK")
        return 0

    if cmd == "check-manifests":
        base = sys.argv[2] if len(sys.argv) > 2 else DOWNLOADS_URL
        errors = check_manifest_urls(base)
        if errors:
            print("Published manifest check failed:", file=sys.stderr)
            for err in errors:
                print(f"  - {err}", file=sys.stderr)
            return 1
        print("Manifests OK")
        return 0

    if cmd in ("validate-entry", "prepare-entry"):
        if len(sys.argv) < 3:
            print(f"{cmd} requires an entry.json path", file=sys.stderr)
            return 2
        if cmd == "prepare-entry":
            prepare_entry_file(sys.argv[2])
            print(f"Entry prepared: {sys.argv[2]}")
            return 0
        with open(sys.argv[2], encoding="utf-8-sig") as f:
            entry = normalize_entry(json.load(f))
        errors = validate_entry_dict(entry)
        if errors:
            print("Release entry validation failed:", file=sys.stderr)
            for err in errors:
                print(f"  - {err}", file=sys.stderr)
            return 1
        print(f"Entry OK: {entry.get('platform')} {entry.get('label')}")
        return 0

    if cmd == "write-entry-b64":
        if len(sys.argv) < 3:
            print("write-entry-b64 requires an output path", file=sys.stderr)
            return 2
        b64 = os.environ.get("ENTRY_B64", "")
        if not b64:
            print("ENTRY_B64 is required", file=sys.stderr)
            return 2
        write_entry_from_b64(sys.argv[2], b64)
        print(f"Entry written: {sys.argv[2]}")
        return 0

    if len(sys.argv) < 3:
        print(f"{cmd} requires a manifest directory", file=sys.stderr)
        return 2

    dir_path = sys.argv[2]

    if cmd == "validate":
        errors = validate_dir(dir_path, artifacts="--artifacts" in sys.argv[3:])
        if errors:
            print("Release manifest validation failed:", file=sys.stderr)
            for err in errors:
                print(f"  - {err}", file=sys.stderr)
            return 1
        print("Manifests OK")
        return 0

    if cmd == "repair":
        print(f"Repaired {repair_dir(dir_path)} field(s) in {dir_path}")
        return 0

    if cmd == "merge":
        if len(sys.argv) < 4:
            print("merge requires an entry.json path", file=sys.stderr)
            return 2
        with open(sys.argv[3], encoding="utf-8-sig") as f:
            entry = json.load(f)
        merge_entry(dir_path, entry)
        print(f"Merged {entry.get('platform')} {entry.get('label')} into {dir_path}")
        return 0

    if cmd == "purge-platform":
        if len(sys.argv) < 4:
            print("purge-platform requires <dir> <platform>", file=sys.stderr)
            return 2
        removed = purge_platform(dir_path, sys.argv[3])
        print(f"Purged {sys.argv[3]} from {dir_path} ({len(removed)} entries)")
        for name in removed:
            print(name)
        return 0

    print(f"Unknown command: {cmd}\n\n{USAGE}", file=sys.stderr)
    return 2


if __name__ == "__main__":
    if len(sys.argv) == 2 and sys.argv[1] == "--self-test":
        self_test()
        print("release-manifest self-test OK")
        raise SystemExit(0)
    raise SystemExit(main())
